export const BirdConstants = {
  JUMP_HEIGHT: 6,
  FALL_HEIGHT: 4,
  SPIN_INCREMENT: 3,
  SIZE: 50,
  INDENT_LEFT: 150,
  BIRD_HEIGHT: 125,
  START_HIT_X: 200,
  END_HIT_X: 44,
  BIRD_JUMP_COUNTER: 22,
};
